### ISSUE TITLE
front 環境構築

### ISSUE THREAD

**Issue by atsuh1r0** [t0d4/wifi-info-dashboard#1]
- next.js
- electron
だけ一旦入れてみる。

https://github.com/saltyshiomix/nextron
nextronというものがあったので、そちらを採用してみた

**Comment by t0d4** [comment]
Electronを使うということは、イメージとしてはプラットフォーム非依存なデスクトップアプリケーションになるという感じですかね？

**Comment by atsuh1r0** [comment]
一昨日のミーティングでElectronの話があった気がしたので、とりあえずインストールしてみた感じです。

mac windowsの両OSのアプリケーションが作れるっぽい？ですが、今回はプレゼンで見せるだけなので、そこまで気にしてなかったです

**Comment by t0d4** [comment]
違和感があったとかそういうわけでは全然なくて、Electronをどう使っていくイメージなのかな？ってちょっと気になっただけです！
ありがとうございます〜
